networks:
  servers:

services:
  balancer:
    build: .
    command: "lb"
    networks:
      - servers
    ports:
      - "8090:8090"

  server1:
    build: .
    command: "server"
    networks:
      - servers
    environment:
      - DB_SERVICE_ADDR=http://db:8081

  server2:
    build: .
    command: "server"
    networks:
      - servers
    environment:
      - DB_SERVICE_ADDR=http://db:8081

  server3:
    build: .
    command: "server"
    networks:
      - servers
    environment:
      - DB_SERVICE_ADDR=http://db:8081

  db:
    build: .
    command: "db"
    networks:
      - servers
    volumes:
      - db-data:/data
    ports:
      - "8083:8081"

volumes:
  db-data:
